### List all plants
GET {{localhost}}/{{api}}/

### Get plant (DefaultBonsai123)
GET {{localhost}}/{{api}}/{{bonsai}}

### Water plant (DefaultBonsai123)
POST {{localhost}}/{{api}}/water/{{bonsai}}

###DELETE a plant (DefaultBonsai123)
DELETE {{localhost}}/{{api}}/{{bonsai}}